
-- All countries

INSERT INTO `country` (`id`, `code`, `name`, `phone`, `currency_symbol`, `capital`, `currency`, `continent`, `continent_code`, `alpha_3`) VALUES
(1, 'AF', 'Afghanistan', 93, '؋', 'Kabul', 'AFN', 'Asia', 'AS', 'AFG'),
(2, 'AX', 'Åland Islands', 358, '€', 'Mariehamn', 'EUR', 'Europe', 'EU', 'ALA'),
(3, 'AL', 'Albania', 355, 'Lek', 'Tirana', 'ALL', 'Europe', 'EU', 'ALB'),
(4, 'DZ', 'Algeria', 213, 'دج', 'Algiers', 'DZD', 'Africa', 'AF', 'DZA'),
(5, 'AS', 'American Samoa', 1, '$', 'Pago Pago', 'USD', 'Australia (Oceania)', 'OC', 'ASM'),
(6, 'AD', 'Andorra', 376, '€', 'Andorra la Vella', 'EUR', 'Europe', 'EU', 'AND'),
(7, 'AO', 'Angola', 244, 'Kz', 'Luanda', 'AOA', 'Africa', 'AF', 'AGO'),
(8, 'AI', 'Anguilla', 1, '$', 'The Valley', 'XCD', 'North America', 'NA', 'AIA'),
(9, 'AQ', 'Antarctica', 672, '$', 'Antarctica', 'AAD', 'Antarctica', 'AN', 'ATA'),
(10, 'AG', 'Antigua and Barbuda', 1, '$', 'St. John\'s', 'XCD', 'North America', 'NA', 'ATG'),
(11, 'AR', 'Argentina', 54, '$', 'Buenos Aires', 'ARS', 'South America', 'SA', 'ARG'),
(12, 'AM', 'Armenia', 374, '֏', 'Yerevan', 'AMD', 'Asia', 'AS', 'ARM'),
(13, 'AW', 'Aruba', 297, 'ƒ', 'Oranjestad', 'AWG', 'North America', 'NA', 'ABW'),
(14, 'AU', 'Australia', 61, '$', 'Canberra', 'AUD', 'Australia (Oceania)', 'OC', 'AUS'),
(15, 'AT', 'Austria', 43, '€', 'Vienna', 'EUR', 'Europe', 'EU', 'AUT'),
(16, 'AZ', 'Azerbaijan', 994, 'm', 'Baku', 'AZN', 'Asia', 'AS', 'AZE'),
(17, 'BS', 'Bahamas', 1, 'B$', 'Nassau', 'BSD', 'North America', 'NA', 'BHS'),
(18, 'BH', 'Bahrain', 973, '.د.ب', 'Manama', 'BHD', 'Asia', 'AS', 'BHR'),
(19, 'BD', 'Bangladesh', 880, '৳', 'Dhaka', 'BDT', 'Asia', 'AS', 'BGD'),
(20, 'BB', 'Barbados', 1, 'Bds$', 'Bridgetown', 'BBD', 'North America', 'NA', 'BRB'),
(21, 'BY', 'Belarus', 375, 'Br', 'Minsk', 'BYN', 'Europe', 'EU', 'BLR'),
(22, 'BE', 'Belgium', 32, '€', 'Brussels', 'EUR', 'Europe', 'EU', 'BEL'),
(23, 'BZ', 'Belize', 501, '$', 'Belmopan', 'BZD', 'North America', 'NA', 'BLZ'),
(24, 'BJ', 'Benin', 229, 'CFA', 'Porto-Novo', 'XOF', 'Africa', 'AF', 'BEN'),
(25, 'BM', 'Bermuda', 1, '$', 'Hamilton', 'BMD', 'North America', 'NA', 'BMU'),
(26, 'BT', 'Bhutan', 975, 'Nu.', 'Thimphu', 'BTN', 'Asia', 'AS', 'BTN'),
(27, 'BO', 'Bolivia (Plurinational State of)', 591, 'Bs.', 'Sucre', 'BOB', 'South America', 'SA', 'BOL'),
(28, 'BA', 'Bosnia and Herzegovina', 387, 'KM', 'Sarajevo', 'BAM', 'Europe', 'EU', 'BIH'),
(29, 'BW', 'Botswana', 267, 'P', 'Gaborone', 'BWP', 'Africa', 'AF', 'BWA'),
(30, 'BV', 'Bouvet Island', 55, 'kr', '', 'NOK', 'Antarctica', 'AN', 'BVT'),
(31, 'BR', 'Brazil', 55, 'R$', 'Brasilia', 'BRL', 'South America', 'SA', 'BRA'),
(32, 'IO', 'British Indian Ocean Territory', 246, '$', 'Diego Garcia', 'USD', 'Asia', 'AS', 'IOT'),
(33, 'BN', 'Brunei Darussalam', 673, 'B$', 'Bandar Seri Begawan', 'BND', 'Asia', 'AS', 'BRN'),
(34, 'BG', 'Bulgaria', 359, 'Лв.', 'Sofia', 'BGN', 'Europe', 'EU', 'BGR'),
(35, 'BF', 'Burkina Faso', 226, 'CFA', 'Ouagadougou', 'XOF', 'Africa', 'AF', 'BFA'),
(36, 'BI', 'Burundi', 257, 'FBu', 'Bujumbura', 'BIF', 'Africa', 'AF', 'BDI'),
(37, 'CV', 'Cabo Verde', 238, '$', 'Praia', 'CVE', 'Africa', 'AF', 'CPV'),
(38, 'KH', 'Cambodia', 855, 'KHR', 'Phnom Penh', 'KHR', 'Asia', 'AS', 'KHM'),
(39, 'CM', 'Cameroon', 237, 'FCFA', 'Yaounde', 'XAF', 'Africa', 'AF', 'CMR'),
(40, 'CA', 'Canada', 1, '$', 'Ottawa', 'CAD', 'North America', 'NA', 'CAN'),
(41, 'BQ', 'Caribbean Netherlands', 599, '$', 'Kralendijk', 'USD', 'North America', 'NA', 'BES'),
(42, 'KY', 'Cayman Islands', 1, '$', 'George Town', 'KYD', 'North America', 'NA', 'CYM'),
(43, 'CF', 'Central African Republic', 236, 'FCFA', 'Bangui', 'XAF', 'Africa', 'AF', 'CAF'),
(44, 'TD', 'Chad', 235, 'FCFA', 'N\'Djamena', 'XAF', 'Africa', 'AF', 'TCD'),
(45, 'CL', 'Chile', 56, '$', 'Santiago', 'CLP', 'South America', 'SA', 'CHL'),
(46, 'CN', 'China', 86, '¥', 'Beijing', 'CNY', 'Asia', 'AS', 'CHN'),
(47, 'CX', 'Christmas Island', 61, '$', 'Flying Fish Cove', 'AUD', 'Asia', 'AS', 'CXR'),
(48, 'CC', 'Cocos (Keeling) Islands', 61, '$', 'West Island', 'AUD', 'Asia', 'AS', 'CCK'),
(49, 'CO', 'Colombia', 57, '$', 'Bogota', 'COP', 'South America', 'SA', 'COL'),
(50, 'KM', 'Comoros', 269, 'CF', 'Moroni', 'KMF', 'Africa', 'AF', 'COM'),
(51, 'CG', 'Congo', 242, 'FC', 'Brazzaville', 'XAF', 'Africa', 'AF', 'COG'),
(52, 'CD', 'Congo, Democratic Republic of the', 243, 'FC', 'Kinshasa', 'CDF', 'Africa', 'AF', 'COD'),
(53, 'CK', 'Cook Islands', 682, '$', 'Avarua', 'NZD', 'Australia (Oceania)', 'OC', 'COK'),
(54, 'CR', 'Costa Rica', 506, '₡', 'San Jose', 'CRC', 'North America', 'NA', 'CRI'),
(55, 'HR', 'Croatia', 385, 'kn', 'Zagreb', 'HRK', 'Europe', 'EU', 'HRV'),
(56, 'CU', 'Cuba', 53, '$', 'Havana', 'CUP', 'North America', 'NA', 'CUB'),
(57, 'CW', 'Curaçao', 599, 'ƒ', 'Willemstad', 'ANG', 'North America', 'NA', 'CUW'),
(58, 'CY', 'Cyprus', 357, '€', 'Nicosia', 'EUR', 'Asia', 'AS', 'CYP'),
(59, 'CZ', 'Czech Republic', 420, 'Kč', 'Prague', 'CZK', 'Europe', 'EU', 'CZE'),
(60, 'CI', 'Côte d\'Ivoire', 225, 'CFA', 'Yamoussoukro', 'XOF', 'Africa', 'AF', 'CIV'),
(61, 'DK', 'Denmark', 45, 'Kr.', 'Copenhagen', 'DKK', 'Europe', 'EU', 'DNK'),
(62, 'DJ', 'Djibouti', 253, 'Fdj', 'Djibouti', 'DJF', 'Africa', 'AF', 'DJI'),
(63, 'DM', 'Dominica', 1, '$', 'Roseau', 'XCD', 'North America', 'NA', 'DMA'),
(64, 'DO', 'Dominican Republic', 1, '$', 'Santo Domingo', 'DOP', 'North America', 'NA', 'DOM'),
(65, 'EC', 'Ecuador', 593, '$', 'Quito', 'USD', 'South America', 'SA', 'ECU'),
(66, 'EG', 'Egypt', 20, 'ج.م', 'Cairo', 'EGP', 'Africa', 'AF', 'EGY'),
(67, 'SV', 'El Salvador', 503, '$', 'San Salvador', 'USD', 'North America', 'NA', 'SLV'),
(68, 'GQ', 'Equatorial Guinea', 240, 'FCFA', 'Malabo', 'XAF', 'Africa', 'AF', 'GNQ'),
(69, 'ER', 'Eritrea', 291, 'Nfk', 'Asmara', 'ERN', 'Africa', 'AF', 'ERI'),
(70, 'EE', 'Estonia', 372, '€', 'Tallinn', 'EUR', 'Europe', 'EU', 'EST'),
(71, 'SZ', 'Eswatini (Swaziland)', 268, 'E', 'Mbabane', 'SZL', 'Africa', 'AF', 'SWZ'),
(72, 'ET', 'Ethiopia', 251, 'Nkf', 'Addis Ababa', 'ETB', 'Africa', 'AF', 'ETH'),
(73, 'FK', 'Falkland Islands (Malvinas)', 500, '£', 'Stanley', 'FKP', 'South America', 'SA', 'FLK'),
(74, 'FO', 'Faroe Islands', 298, 'Kr.', 'Torshavn', 'DKK', 'Europe', 'EU', 'FRO'),
(75, 'FJ', 'Fiji', 679, 'FJ$', 'Suva', 'FJD', 'Australia (Oceania)', 'OC', 'FJI'),
(76, 'FI', 'Finland', 358, '€', 'Helsinki', 'EUR', 'Europe', 'EU', 'FIN'),
(77, 'FR', 'France', 33, '€', 'Paris', 'EUR', 'Europe', 'EU', 'FRA'),
(78, 'GF', 'French Guiana', 594, '€', 'Cayenne', 'EUR', 'South America', 'SA', 'GUF'),
(79, 'PF', 'French Polynesia', 689, '₣', 'Papeete', 'XPF', 'Australia (Oceania)', 'OC', 'PYF'),
(80, 'TF', 'French Southern Territories', 262, '€', 'Port-aux-Francais', 'EUR', 'Antarctica', 'AN', 'ATF'),
(81, 'GA', 'Gabon', 241, 'FCFA', 'Libreville', 'XAF', 'Africa', 'AF', 'GAB'),
(82, 'GM', 'Gambia', 220, 'D', 'Banjul', 'GMD', 'Africa', 'AF', 'GMB'),
(83, 'GE', 'Georgia', 995, 'ლ', 'Tbilisi', 'GEL', 'Asia', 'AS', 'GEO'),
(84, 'DE', 'Germany', 49, '€', 'Berlin', 'EUR', 'Europe', 'EU', 'DEU'),
(85, 'GH', 'Ghana', 233, 'GH₵', 'Accra', 'GHS', 'Africa', 'AF', 'GHA'),
(86, 'GI', 'Gibraltar', 350, '£', 'Gibraltar', 'GIP', 'Europe', 'EU', 'GIB'),
(87, 'GR', 'Greece', 30, '€', 'Athens', 'EUR', 'Europe', 'EU', 'GRC'),
(88, 'GL', 'Greenland', 299, 'Kr.', 'Nuuk', 'DKK', 'North America', 'NA', 'GRL'),
(89, 'GD', 'Grenada', 1, '$', 'St. George\'s', 'XCD', 'North America', 'NA', 'GRD'),
(90, 'GP', 'Guadeloupe', 590, '€', 'Basse-Terre', 'EUR', 'North America', 'NA', 'GLP'),
(91, 'GU', 'Guam', 1, '$', 'Hagatna', 'USD', 'Australia (Oceania)', 'OC', 'GUM'),
(92, 'GT', 'Guatemala', 502, 'Q', 'Guatemala City', 'GTQ', 'North America', 'NA', 'GTM'),
(93, 'GG', 'Guernsey', 44, '£', 'St Peter Port', 'GBP', 'Europe', 'EU', 'GGY'),
(94, 'GN', 'Guinea', 224, 'FG', 'Conakry', 'GNF', 'Africa', 'AF', 'GIN'),
(95, 'GW', 'Guinea-Bissau', 245, 'CFA', 'Bissau', 'XOF', 'Africa', 'AF', 'GNB'),
(96, 'GY', 'Guyana', 592, '$', 'Georgetown', 'GYD', 'South America', 'SA', 'GUY'),
(97, 'HT', 'Haiti', 509, 'G', 'Port-au-Prince', 'HTG', 'North America', 'NA', 'HTI'),
(98, 'HM', 'Heard Island and Mcdonald Islands', 61, '$', '', 'AUD', 'Antarctica', 'AN', 'HMD'),
(99, 'HN', 'Honduras', 504, 'L', 'Tegucigalpa', 'HNL', 'North America', 'NA', 'HND'),
(100, 'HK', 'Hong Kong', 852, '$', 'Hong Kong', 'HKD', 'Asia', 'AS', 'HKG'),
(101, 'HU', 'Hungary', 36, 'Ft', 'Budapest', 'HUF', 'Europe', 'EU', 'HUN'),
(102, 'IS', 'Iceland', 354, 'kr', 'Reykjavik', 'ISK', 'Europe', 'EU', 'ISL'),
(103, 'IN', 'India', 91, '₹', 'New Delhi', 'INR', 'Asia', 'AS', 'IND'),
(104, 'ID', 'Indonesia', 62, 'Rp', 'Jakarta', 'IDR', 'Asia', 'AS', 'IDN'),
(105, 'IR', 'Iran', 98, '﷼', 'Tehran', 'IRR', 'Asia', 'AS', 'IRN'),
(106, 'IQ', 'Iraq', 964, 'د.ع', 'Baghdad', 'IQD', 'Asia', 'AS', 'IRQ'),
(107, 'IE', 'Ireland', 353, '€', 'Dublin', 'EUR', 'Europe', 'EU', 'IRL'),
(108, 'IM', 'Isle of Man', 44, '£', 'Douglas, Isle of Man', 'GBP', 'Europe', 'EU', 'IMN'),
(109, 'IL', 'Israel', 972, '₪', 'Jerusalem', 'ILS', 'Asia', 'AS', 'ISR'),
(110, 'IT', 'Italy', 39, '€', 'Rome', 'EUR', 'Europe', 'EU', 'ITA'),
(111, 'JM', 'Jamaica', 1, 'J$', 'Kingston', 'JMD', 'North America', 'NA', 'JAM'),
(112, 'JP', 'Japan', 81, '¥', 'Tokyo', 'JPY', 'Asia', 'AS', 'JPN'),
(113, 'JE', 'Jersey', 44, '£', 'Saint Helier', 'GBP', 'Europe', 'EU', 'JEY'),
(114, 'JO', 'Jordan', 962, 'ا.د', 'Amman', 'JOD', 'Asia', 'AS', 'JOR'),
(115, 'KZ', 'Kazakhstan', 7, 'лв', 'Astana', 'KZT', 'Asia', 'AS', 'KAZ'),
(116, 'KE', 'Kenya', 254, 'KSh', 'Nairobi', 'KES', 'Africa', 'AF', 'KEN'),
(117, 'KI', 'Kiribati', 686, '$', 'Tarawa', 'AUD', 'Australia (Oceania)', 'OC', 'KIR'),
(118, 'KP', 'Korea, North', 850, '₩', 'Pyongyang', 'KPW', 'Asia', 'AS', 'PRK'),
(119, 'KR', 'Korea, South', 82, '₩', 'Seoul', 'KRW', 'Asia', 'AS', 'KOR'),
(120, 'XK', 'Kosovo', 383, '€', 'Pristina', 'EUR', 'Europe', 'EU', 'XKX'),
(121, 'KW', 'Kuwait', 965, 'ك.د', 'Kuwait City', 'KWD', 'Asia', 'AS', 'KWT'),
(122, 'KG', 'Kyrgyzstan', 996, 'лв', 'Bishkek', 'KGS', 'Asia', 'AS', 'KGZ'),
(123, 'LA', 'Lao People\'s Democratic Republic', 856, '₭', 'Vientiane', 'LAK', 'Asia', 'AS', 'LAO'),
(124, 'LV', 'Latvia', 371, '€', 'Riga', 'EUR', 'Europe', 'EU', 'LVA'),
(125, 'LB', 'Lebanon', 961, '£', 'Beirut', 'LBP', 'Asia', 'AS', 'LBN'),
(126, 'LS', 'Lesotho', 266, 'L', 'Maseru', 'LSL', 'Africa', 'AF', 'LSO'),
(127, 'LR', 'Liberia', 231, '$', 'Monrovia', 'LRD', 'Africa', 'AF', 'LBR'),
(128, 'LY', 'Libya', 218, 'د.ل', 'Tripolis', 'LYD', 'Africa', 'AF', 'LBY'),
(129, 'LI', 'Liechtenstein', 423, 'CHf', 'Vaduz', 'CHF', 'Europe', 'EU', 'LIE'),
(130, 'LT', 'Lithuania', 370, '€', 'Vilnius', 'EUR', 'Europe', 'EU', 'LTU'),
(131, 'LU', 'Luxembourg', 352, '€', 'Luxembourg', 'EUR', 'Europe', 'EU', 'LUX'),
(132, 'MO', 'Macao', 853, '$', 'Macao', 'MOP', 'Asia', 'AS', 'MAC'),
(133, 'MK', 'Macedonia North', 389, 'ден', 'Skopje', 'MKD', 'Europe', 'EU', 'MKD'),
(134, 'MG', 'Madagascar', 261, 'Ar', 'Antananarivo', 'MGA', 'Africa', 'AF', 'MDG'),
(135, 'MW', 'Malawi', 265, 'MK', 'Lilongwe', 'MWK', 'Africa', 'AF', 'MWI'),
(136, 'MY', 'Malaysia', 60, 'RM', 'Kuala Lumpur', 'MYR', 'Asia', 'AS', 'MYS'),
(137, 'MV', 'Maldives', 960, 'Rf', 'Male', 'MVR', 'Asia', 'AS', 'MDV'),
(138, 'ML', 'Mali', 223, 'CFA', 'Bamako', 'XOF', 'Africa', 'AF', 'MLI'),
(139, 'MT', 'Malta', 356, '€', 'Valletta', 'EUR', 'Europe', 'EU', 'MLT'),
(140, 'MH', 'Marshall Islands', 692, '$', 'Majuro', 'USD', 'Australia (Oceania)', 'OC', 'MHL'),
(141, 'MQ', 'Martinique', 596, '€', 'Fort-de-France', 'EUR', 'North America', 'NA', 'MTQ'),
(142, 'MR', 'Mauritania', 222, 'MRU', 'Nouakchott', 'MRO', 'Africa', 'AF', 'MRT'),
(143, 'MU', 'Mauritius', 230, '₨', 'Port Louis', 'MUR', 'Africa', 'AF', 'MUS'),
(144, 'YT', 'Mayotte', 262, '€', 'Mamoudzou', 'EUR', 'Africa', 'AF', 'MYT'),
(145, 'MX', 'Mexico', 52, '$', 'Mexico City', 'MXN', 'North America', 'NA', 'MEX'),
(146, 'FM', 'Micronesia', 691, '$', 'Palikir', 'USD', 'Australia (Oceania)', 'OC', 'FSM'),
(147, 'MD', 'Moldova', 373, 'L', 'Chisinau', 'MDL', 'Europe', 'EU', 'MDA'),
(148, 'MC', 'Monaco', 377, '€', 'Monaco', 'EUR', 'Europe', 'EU', 'MCO'),
(149, 'MN', 'Mongolia', 976, '₮', 'Ulan Bator', 'MNT', 'Asia', 'AS', 'MNG'),
(150, 'ME', 'Montenegro', 382, '€', 'Podgorica', 'EUR', 'Europe', 'EU', 'MNE'),
(151, 'MS', 'Montserrat', 1, '$', 'Plymouth', 'XCD', 'North America', 'NA', 'MSR'),
(152, 'MA', 'Morocco', 212, 'DH', 'Rabat', 'MAD', 'Africa', 'AF', 'MAR'),
(153, 'MZ', 'Mozambique', 258, 'MT', 'Maputo', 'MZN', 'Africa', 'AF', 'MOZ'),
(154, 'MM', 'Myanmar (Burma)', 95, 'K', 'Nay Pyi Taw', 'MMK', 'Asia', 'AS', 'MMR'),
(155, 'NA', 'Namibia', 264, '$', 'Windhoek', 'NAD', 'Africa', 'AF', 'NAM'),
(156, 'NR', 'Nauru', 674, '$', 'Yaren', 'AUD', 'Australia (Oceania)', 'OC', 'NRU'),
(157, 'NP', 'Nepal', 977, '₨', 'Kathmandu', 'NPR', 'Asia', 'AS', 'NPL'),
(158, 'NL', 'Netherlands', 31, '€', 'Amsterdam', 'EUR', 'Europe', 'EU', 'NLD'),
(159, 'AN', 'Netherlands Antilles', 599, 'NAf', 'Willemstad', 'ANG', 'North America', 'NA', 'ANT'),
(160, 'NC', 'New Caledonia', 687, '₣', 'Noumea', 'XPF', 'Australia (Oceania)', 'OC', 'NCL'),
(161, 'NZ', 'New Zealand', 64, '$', 'Wellington', 'NZD', 'Australia (Oceania)', 'OC', 'NZL'),
(162, 'NI', 'Nicaragua', 505, 'C$', 'Managua', 'NIO', 'North America', 'NA', 'NIC'),
(163, 'NE', 'Niger', 227, 'CFA', 'Niamey', 'XOF', 'Africa', 'AF', 'NER'),
(164, 'NG', 'Nigeria', 234, '₦', 'Abuja', 'NGN', 'Africa', 'AF', 'NGA'),
(165, 'NU', 'Niue', 683, '$', 'Alofi', 'NZD', 'Australia (Oceania)', 'OC', 'NIU'),
(166, 'NF', 'Norfolk Island', 672, '$', 'Kingston', 'AUD', 'Australia (Oceania)', 'OC', 'NFK'),
(167, 'MP', 'Northern Mariana Islands', 1, '$', 'Saipan', 'USD', 'Australia (Oceania)', 'OC', 'MNP'),
(168, 'NO', 'Norway', 47, 'kr', 'Oslo', 'NOK', 'Europe', 'EU', 'NOR'),
(169, 'OM', 'Oman', 968, '.ع.ر', 'Muscat', 'OMR', 'Asia', 'AS', 'OMN'),
(170, 'PK', 'Pakistan', 92, '₨', 'Islamabad', 'PKR', 'Asia', 'AS', 'PAK'),
(171, 'PW', 'Palau', 680, '$', 'Melekeok', 'USD', 'Australia (Oceania)', 'OC', 'PLW'),
(172, 'PS', 'Palestine', 970, '₪', 'East Jerusalem', 'ILS', 'Asia', 'AS', 'PSE'),
(173, 'PA', 'Panama', 507, 'B/.', 'Panama City', 'PAB', 'North America', 'NA', 'PAN'),
(174, 'PG', 'Papua New Guinea', 675, 'K', 'Port Moresby', 'PGK', 'Australia (Oceania)', 'OC', 'PNG'),
(175, 'PY', 'Paraguay', 595, '₲', 'Asuncion', 'PYG', 'South America', 'SA', 'PRY'),
(176, 'PE', 'Peru', 51, 'S/.', 'Lima', 'PEN', 'South America', 'SA', 'PER'),
(177, 'PH', 'Philippines', 63, '₱', 'Manila', 'PHP', 'Asia', 'AS', 'PHL'),
(178, 'PN', 'Pitcairn Islands', 64, '$', 'Adamstown', 'NZD', 'Australia (Oceania)', 'OC', 'PCN'),
(179, 'PL', 'Poland', 48, 'zł', 'Warsaw', 'PLN', 'Europe', 'EU', 'POL'),
(180, 'PT', 'Portugal', 351, '€', 'Lisbon', 'EUR', 'Europe', 'EU', 'PRT'),
(181, 'PR', 'Puerto Rico', 1, '$', 'San Juan', 'USD', 'North America', 'NA', 'PRI'),
(182, 'QA', 'Qatar', 974, 'ق.ر', 'Doha', 'QAR', 'Asia', 'AS', 'QAT'),
(183, 'RE', 'Reunion', 262, '€', 'Saint-Denis', 'EUR', 'Africa', 'AF', 'REU'),
(184, 'RO', 'Romania', 40, 'lei', 'Bucharest', 'RON', 'Europe', 'EU', 'ROM'),
(185, 'RU', 'Russian Federation', 7, '₽', 'Moscow', 'RUB', 'Asia', 'AS', 'RUS'),
(186, 'RW', 'Rwanda', 250, 'FRw', 'Kigali', 'RWF', 'Africa', 'AF', 'RWA'),
(187, 'BL', 'Saint Barthelemy', 590, '€', 'Gustavia', 'EUR', 'North America', 'NA', 'BLM'),
(188, 'SH', 'Saint Helena', 290, '£', 'Jamestown', 'SHP', 'Africa', 'AF', 'SHN'),
(189, 'KN', 'Saint Kitts and Nevis', 1, '$', 'Basseterre', 'XCD', 'North America', 'NA', 'KNA'),
(190, 'LC', 'Saint Lucia', 1, '$', 'Castries', 'XCD', 'North America', 'NA', 'LCA'),
(191, 'MF', 'Saint Martin', 590, '€', 'Marigot', 'EUR', 'North America', 'NA', 'MAF'),
(192, 'PM', 'Saint Pierre and Miquelon', 508, '€', 'Saint-Pierre', 'EUR', 'North America', 'NA', 'SPM'),
(193, 'VC', 'Saint Vincent and the Grenadines', 1, '$', 'Kingstown', 'XCD', 'North America', 'NA', 'VCT'),
(194, 'WS', 'Samoa', 685, 'SAT', 'Apia', 'WST', 'Australia (Oceania)', 'OC', 'WSM'),
(195, 'SM', 'San Marino', 378, '€', 'San Marino', 'EUR', 'Europe', 'EU', 'SMR'),
(196, 'ST', 'Sao Tome and Principe', 239, 'Db', 'Sao Tome', 'STD', 'Africa', 'AF', 'STP'),
(197, 'SA', 'Saudi Arabia', 966, '﷼', 'Riyadh', 'SAR', 'Asia', 'AS', 'SAU'),
(198, 'SN', 'Senegal', 221, 'CFA', 'Dakar', 'XOF', 'Africa', 'AF', 'SEN'),
(199, 'RS', 'Serbia', 381, 'din', 'Belgrade', 'RSD', 'Europe', 'EU', 'SRB'),
(200, 'CS', 'Serbia and Montenegro', 381, 'din', 'Belgrade', 'RSD', 'Europe', 'EU', 'SCG'),
(201, 'SC', 'Seychelles', 248, 'SRe', 'Victoria', 'SCR', 'Africa', 'AF', 'SYC'),
(202, 'SL', 'Sierra Leone', 232, 'Le', 'Freetown', 'SLL', 'Africa', 'AF', 'SLE'),
(203, 'SG', 'Singapore', 65, '$', 'Singapur', 'SGD', 'Asia', 'AS', 'SGP'),
(204, 'SX', 'Sint Maarten', 1, 'ƒ', 'Philipsburg', 'ANG', 'North America', 'NA', 'SXM'),
(205, 'SK', 'Slovakia', 421, '€', 'Bratislava', 'EUR', 'Europe', 'EU', 'SVK'),
(206, 'SI', 'Slovenia', 386, '€', 'Ljubljana', 'EUR', 'Europe', 'EU', 'SVN'),
(207, 'SB', 'Solomon Islands', 677, 'Si$', 'Honiara', 'SBD', 'Australia (Oceania)', 'OC', 'SLB'),
(208, 'SO', 'Somalia', 252, 'Sh.so.', 'Mogadishu', 'SOS', 'Africa', 'AF', 'SOM'),
(209, 'ZA', 'South Africa', 27, 'R', 'Pretoria', 'ZAR', 'Africa', 'AF', 'ZAF'),
(210, 'GS', 'South Georgia and the South Sandwich Islands', 500, '£', 'Grytviken', 'GBP', 'Antarctica', 'AN', 'SGS'),
(211, 'SS', 'South Sudan', 211, '£', 'Juba', 'SSP', 'Africa', 'AF', 'SSD'),
(212, 'ES', 'Spain', 34, '€', 'Madrid', 'EUR', 'Europe', 'EU', 'ESP'),
(213, 'LK', 'Sri Lanka', 94, 'Rs', 'Colombo', 'LKR', 'Asia', 'AS', 'LKA'),
(214, 'SD', 'Sudan', 249, '.س.ج', 'Khartoum', 'SDG', 'Africa', 'AF', 'SDN'),
(215, 'SR', 'Suriname', 597, '$', 'Paramaribo', 'SRD', 'South America', 'SA', 'SUR'),
(216, 'SJ', 'Svalbard and Jan Mayen', 47, 'kr', 'Longyearbyen', 'NOK', 'Europe', 'EU', 'SJM'),
(217, 'SE', 'Sweden', 46, 'kr', 'Stockholm', 'SEK', 'Europe', 'EU', 'SWE'),
(218, 'CH', 'Switzerland', 41, 'CHf', 'Berne', 'CHF', 'Europe', 'EU', 'CHE'),
(219, 'SY', 'Syria', 963, 'LS', 'Damascus', 'SYP', 'Asia', 'AS', 'SYR'),
(220, 'TW', 'Taiwan', 886, '$', 'Taipei', 'TWD', 'Asia', 'AS', 'TWN'),
(221, 'TJ', 'Tajikistan', 992, 'SM', 'Dushanbe', 'TJS', 'Asia', 'AS', 'TJK'),
(222, 'TZ', 'Tanzania', 255, 'TSh', 'Dodoma', 'TZS', 'Africa', 'AF', 'TZA'),
(223, 'TH', 'Thailand', 66, '฿', 'Bangkok', 'THB', 'Asia', 'AS', 'THA'),
(224, 'TL', 'Timor-Leste', 670, '$', 'Dili', 'USD', 'Asia', 'AS', 'TLS'),
(225, 'TG', 'Togo', 228, 'CFA', 'Lome', 'XOF', 'Africa', 'AF', 'TGO'),
(226, 'TK', 'Tokelau', 690, '$', '', 'NZD', 'Australia (Oceania)', 'OC', 'TKL'),
(227, 'TO', 'Tonga', 676, '$', 'Nuku\'alofa', 'TOP', 'Australia (Oceania)', 'OC', 'TON'),
(228, 'TT', 'Trinidad and Tobago', 1, '$', 'Port of Spain', 'TTD', 'North America', 'NA', 'TTO'),
(229, 'TN', 'Tunisia', 216, 'ت.د', 'Tunis', 'TND', 'Africa', 'AF', 'TUN'),
(230, 'TR', 'Turkey (Türkiye)', 90, '₺', 'Ankara', 'TRY', 'Asia', 'AS', 'TUR'),
(231, 'TM', 'Turkmenistan', 993, 'T', 'Ashgabat', 'TMT', 'Asia', 'AS', 'TKM'),
(232, 'TC', 'Turks and Caicos Islands', 1, '$', 'Cockburn Town', 'USD', 'North America', 'NA', 'TCA'),
(233, 'TV', 'Tuvalu', 688, '$', 'Funafuti', 'AUD', 'Australia (Oceania)', 'OC', 'TUV'),
(234, 'UM', 'U.S. Outlying Islands', 1, '$', '', 'USD', 'North America', 'NA', 'UMI'),
(235, 'UG', 'Uganda', 256, 'USh', 'Kampala', 'UGX', 'Africa', 'AF', 'UGA'),
(236, 'UA', 'Ukraine', 380, '₴', 'Kiev', 'UAH', 'Europe', 'EU', 'UKR'),
(237, 'AE', 'United Arab Emirates', 971, 'إ.د', 'Abu Dhabi', 'AED', 'Asia', 'AS', 'ARE'),
(238, 'GB', 'United Kingdom', 44, '£', 'London', 'GBP', 'Europe', 'EU', 'GBR'),
(239, 'US', 'United States', 1, '$', 'Washington', 'USD', 'North America', 'NA', 'USA'),
(240, 'UY', 'Uruguay', 598, '$', 'Montevideo', 'UYU', 'South America', 'SA', 'URY'),
(241, 'UZ', 'Uzbekistan', 998, 'лв', 'Tashkent', 'UZS', 'Asia', 'AS', 'UZB'),
(242, 'VU', 'Vanuatu', 678, 'VT', 'Port Vila', 'VUV', 'Australia (Oceania)', 'OC', 'VUT'),
(243, 'VA', 'Vatican City Holy See', 39, '€', 'Vatican City', 'EUR', 'Europe', 'EU', 'VAT'),
(244, 'VE', 'Venezuela', 58, 'Bs', 'Caracas', 'VEF', 'South America', 'SA', 'VEN'),
(245, 'VN', 'Vietnam', 84, '₫', 'Hanoi', 'VND', 'Asia', 'AS', 'VNM'),
(246, 'VG', 'Virgin Islands, British', 1, '$', 'Road Town', 'USD', 'North America', 'NA', 'VGB'),
(247, 'VI', 'Virgin Islands, U.S', 1, '$', 'Charlotte Amalie', 'USD', 'North America', 'NA', 'VIR'),
(248, 'WF', 'Wallis and Futuna', 681, '₣', 'Mata Utu', 'XPF', 'Australia (Oceania)', 'OC', 'WLF'),
(249, 'EH', 'Western Sahara', 212, 'MAD', 'El-Aaiun', 'MAD', 'Africa', 'AF', 'ESH'),
(250, 'YE', 'Yemen', 967, '﷼', 'Sanaa', 'YER', 'Asia', 'AS', 'YEM'),
(251, 'ZM', 'Zambia', 260, 'ZK', 'Lusaka', 'ZMW', 'Africa', 'AF', 'ZMB'),
(252, 'ZW', 'Zimbabwe', 263, '$', 'Harare', 'ZWL', 'Africa', 'AF', 'ZWE');

-- Continents

INSERT INTO `continent` (`id`, `code`, `name`) VALUES
(1, 'AF', 'Africa'),
(2, 'AN', 'Antarctica'),
(3, 'AS', 'Asia'),
(4, 'EU', 'Europe'),
(5, 'OC', 'Australia'),
(6, 'NA', 'North America'),
(7, 'SA', 'South America');
